### ISSUE TITLE
Duplicated video start calls

### ISSUE THREAD

**Issue by awongwork** [Adobe-Marketing-Cloud/video-heartbeat-v2#18]
With the upgrade to Heartbeat V2, I noticed that, instead of making one "start" call for asset type "main", I'm seeing two, where the first "start" call doesn't contain user info, where as the second does:

![image](https://user-images.githubusercontent.com/4719921/37525014-fb388da2-2901-11e8-9b02-fe8622f20140.png)

To recap, we're seeing
1)  start (w/out user info)
2)  start (w/ user info)
3)  aa_start

Is this the expected behaviour?

**Comment by himanshuphalak** [comment]
Hi @awongwork, yes that is an expected behavior. Multiple start calls just mean time to start the content (if difference between trackSessionStart and trackPlay is > 250ms, then that duration is tracked with another start call). For the user information, that usually starts appearing when aa_start call is processed but it is okay to have it on start call as well.

**Comment by awongwork** [comment]
Thanks @himanshuphalak !  To further clarify, these will not result in duplicated Content Start metrics?

**Comment by himanshuphalak** [comment]
@awongwork yes, that is correct.

**Comment by awongwork** [comment]
Thank you @himanshuphalak
