### ISSUE TITLE
Roku cert issue due to usage of deprecated legacy SDK1 components with SceneGraph app

### ISSUE THREAD

**Issue by sebastiencouture** [Adobe-Marketing-Cloud/video-heartbeat-v2#22]
Roku has begun raising the following issue during certification of SceneGraph apps:

```
Steps to reproduce: 
1. Add the channel to Roku player.
2. Verify that the channel template does not use deprecated elements.

Expected result: channel uses Roku SceneGraph template without deprecated components.
Actual result: channel uses 3rd party libraries that contain SDK1 deprecated components:
Found deprecated roVideoPlayerEvent in file adbmobile.brs, line 2773
Found deprecated roVideoScreenEvent in file adbmobile.brs, line 2773
More info: https://blog.roku.com/developer/2017/02/01/legacy-sdk/
Reproducibility: always
```

adbmobile.brs includes support for both SceneGraph and legacy SDK1 app, but Roku is now requiring that we do not include any legacy SDK1 code with the app so adbmobile.brs needs to be split into two separate libraries: one for scenegraph and one for legacy SDK1 apps

**Comment by himanshuphalak** [comment]
Hi @sebastiencouture, we are using roVideoPlayerEvent and roVideoScreenEvent only in String comparison in ADBVideoPlayer utility class and has been deprecated since last couple of SDK versions. We do plan to remove ADBVideoPlayer code completely with our next release but until then you can work around this by manually stripping out ADBVideoPlayer utility function from our SDK brs file.

**Comment by himanshuphalak** [comment]
@sebastiencouture, is there any further support needed on this? If not, we can close this issue.
