### ISSUE TITLE
Live - program change

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/video-heartbeat-v2#25]
Hi,

When a `program change` happens in LIVE streaming, how do i change the media info. I am not calling `mediaTrackLoad` again, just starting chapter_1. 
So how do we update the new media item details.

Thanks!

**Comment by himanshuphalak** [comment]
Hi @dipan-majumder, Chapter tracking can only be used to track different sections on the same stream, and a stream is defined by MediaInfo which means media information on a given stream can never change. If your media information or custom video metadata changes, then that should be treated as a separate stream. In this use case, since your media information changes on program boundaries, you can end the tracking session and start another with updated media information.

**Comment by dipan-majumder** [comment]
ok, let me try, thanks!

**Comment by dipan-majumder** [comment]
It worked, thanks!
